### ISSUE TITLE
Create birth date field

### ISSUE THREAD

**Issue by cjustice10** [ctl14/TeamFormProject#7]
The birthdate field is required, must be a valid date, and must be at least thirteen years in the past. Each of these validations should have their respective appropriate error messages. Use Date.parse() to parse what the user enters into a timestamp—it will be a NaN if the entered value is not a valid date. If it isn't NaN, you can then compare it to the timestamp for the current date 13 years ago.

You might be tempted to use an <input type="date"> here, but I wouldn't recommend it—that type is not yet supported in Firefox, Safari, and IE, so you'll have to write extra code to handle the different behaviors. Using it also makes writing your automated tests much more difficult, as you will have to account for different user interactions on Chrome vs other browsers.

It's possible to do custom validations (like needed for the birthdate and password fields) using custom directives. However, an easier approach is specify a function that you would like to call whenever the inputs of interest change. You can use the $setValidity() method to change whether a particular property (e.g., 'required', or a label of your choosing) is valid or not.

**Comment by Randert** [comment]
finished up validity check and age check still need to work on automated tests
